### ISSUE TITLE
versioning and releases

### ISSUE THREAD

**Issue by dup2** [evanmiller/mod_zip#40]
Any plans to use versioning and releases for this module? 

We build it with a CI system along with our nginx build and currently track the master branch but this might lead to unstable builds as new code is included automatically. I just switched to a commit-hash based download URI to prevent this, it feels a bit ugly..

Using releases with a versioning scheme would be great! :pray:

**Comment by anthonyryan1** [comment]
Part of the problem here is that this repository is only the recent history and everything from the svn days is lost.

I have tagged the most recent release 1.1.6 from 2010. I expect future releases will follow semantic versioning with the next one likely to be 1.2.0. At the moment though I'd say a bit of testing and bug cleanup is necessary before a new release could be tagged.

**Comment by evanmiller** [comment]
The project is basically in maintenance mode but I have tagged some releases here:

https://github.com/evanmiller/mod_zip/releases
