### ISSUE TITLE
compile error with nginx openresty 1.9.7

### ISSUE THREAD

**Issue by bilalghouri** [evanmiller/mod_zip#51]
openresty compiles without mod_zip (latest github) but with the module, make fails with this error:

objs/src/http/ngx_http_postpone_filter_module.o:(.data+0x0): multiple definition of `ngx_http_postpone_filter_module'
objs/src/http/ngx_http_postpone_filter_module.o:(.data+0x0): first defined here
collect2: error: ld returned 1 exit status
objs/Makefile:362: recipe for target 'objs/nginx' failed
make[2]: *** [objs/nginx] Error 1
make[2]: Leaving directory '/root/openresty-1.9.7.3/build/nginx-1.9.7'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/root/openresty-1.9.7.3/build/nginx-1.9.7'
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 2

compile options:

./configure --without-http_uwsgi_module --without-http_userid_module --without-http_autoindex_module --without-http_auth_basic_module --without-http_ssi_module --without-http_geo_module --with-pcre-jit --with-http_stub_status_module --with-http_mp4_module --add-module=/root/mod_zip

**Comment by bilalghouri** [comment]
--without-http_ssi_module was causing the error.

**Comment by anthonyryan1** [comment]
Hello @bilalghouri,

This issue is my fault. I solved a postpone filter bug that affected both of these plugins, but hadn't given any thought for them both being used at the same time.

https://github.com/evanmiller/mod_zip/pull/46 & https://github.com/openresty/echo-nginx-module/pull/39

I'll give it some thought and see if I can come up with a better solution to address your issue.
